version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: catmash
      POSTGRES_USER: morganballouk
      POSTGRES_PASSWORD: psql
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/catmash

volumes:
  pgdata:
