app = "spring-boot-catmash"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["tls", "http"]
start_port = 443
end_port = 443

[deploy]
release_memory = 2048 # Set memory in MB
